services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - backend-data:/app-data
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      app-net:
      macvlan:
        ipv4_address: 192.168.220.158

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      app-net:
      macvlan:
        ipv4_address: 192.168.220.157

networks:
  app-net:
    driver: bridge
  macvlan:
    external: true

volumes:
  backend-data:
